Repository newrelic/k8s-metadata-injection, pull requests merged in 2023-08, with the labels that each got.

#316 chore: Add CHANGELOG github workflow
  .github/workflows/changelog.yml
  CHANGELOG.md
  CONTRIBUTING.md
Labels: ci/skip-e2e

#318 Update CODEOWNERS
  .github/CODEOWNERS
  CHANGELOG.md
Labels: ci/skip-e2e

#317 chore: Add Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: ci/skip-e2e

#320 chore: Add labels to changelog workflow and renovatebot
  .github/renovate.json5
  .github/workflows/changelog.yml
  CONTRIBUTING.md
Labels: ci/skip-e2e, ci/skip-load-test, Skip Changelog

#319 [Snyk] Security upgrade alpine from 3.18.2 to 3.18.3
  Dockerfile
Labels: dependencies

#328 Update CHANGELOG
  CHANGELOG.md
Labels: ci/skip-e2e, Skip Changelog

#330 Document certificate duration values
  charts/nri-metadata-injection/README.md
Labels: ci/skip-e2e, ci/skip-load-test, Skip Changelog

#331 Bump versions
  charts/nri-metadata-injection/Chart.yaml
Labels: ci/skip-e2e, Skip Changelog

#321 feat: Enable automatic release
  .github/renovate.json5
  .github/workflows/push_pr.yml
  .github/workflows/release-integration.yml
  .github/workflows/security.yaml
  .github/workflows/trigger_prerelease.yml
  .gitignore
  Makefile
Labels: ci/skip-e2e, ci/skip-load-test, Skip Changelog

#322 feat: Remove dependabot
  .github/dependabot.yml
Labels: ci/skip-e2e, ci/skip-load-test, Skip Changelog

#337 tmp: Add debug step to changelog workflow
  .github/workflows/changelog.yml
Labels: Skip Changelog

#342 Fix links
  .github/workflows/release-integration.yml
Labels: ci/skip-e2e, Skip Changelog

#343 Define GitHub bot name and email
  .github/workflows/trigger_prerelease.yml
  CHANGELOG.md
Labels: ci/skip-e2e

#344 chore: fix dockerfile in trigger prerelease workflow
  .github/workflows/trigger_prerelease.yml
Labels: Skip Changelog

#346 testing: Lower dockerfile version
  Dockerfile
Labels: dependencies, Skip Changelog

#340 Exclude renovate changelog
  .github/workflows/changelog.yml
Labels: Skip Changelog

#349 chore: Bump version and app version
  charts/nri-metadata-injection/Chart.yaml
Labels: Skip Changelog

#350 tmp: Testing new workflow to bump versions
  .github/actions/version-bump/action.yml
  .github/actions/version-bump/version-update.js
  .github/workflows/release-integration.yml
Labels: Skip Changelog

#363 fix: Remove tmp test workflow
  .github/workflows/release-integration.yml
  src/utils/version-update.go
Labels: Skip Changelog
